[package]
name = "sudoku"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
crossterm = "0.27.0"
ratatui = "0.25.0"
regex = "1.10.3"
tempfile = "3.9.0"
